package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("Playtika tests")
    void generatedTest() {
        step("Open https://www.playtika.com/", () -> {
            step("// todo: just add selenium action");
        });

        step("Navigate to Careers tab", () -> {
            step("// todo: just add selenium action");
        });

        step("Choose QA section", () -> {
            step("// todo: just add selenium action");
        });

        step("Choose Ukraine", () -> {
            step("// todo: just add selenium action");
        });

        step("Enter QA Automation Engineer into Search field", () -> {
            step("// todo: just add selenium action");
        });

        step("Verify QA Automation Engineer position exists in Kyiv", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://www.playtika.com/'", () ->
            open("https://www.playtika.com/"));

        step("Page title should have text 'Playtika - Infinite Ways to Play'", () -> {
            String expectedTitle = "Playtika - Infinite Ways to Play";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://www.playtika.com/'", () ->
            open("https://www.playtika.com/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}